### ISSUE TITLE
大佬，对于反代需要用https该怎么处理

### ISSUE THREAD

**Issue by WL0627** [shenxianmq/Auto_Symlink#11]
我是群辉主机，目前jellyfin和alist都是用了反代统一端口，目前用本工具生成好的strm文件需要在strm内手动将http变更为 https才能访问。例如：http://xx.xxx:88/d/xxx是不能访问的，变更为https://xx.xxx:88/d/xxx能正常访问

**Comment by shenxianmq** [comment]
你的alist地址直接填你反代的https地址就可以了

**Comment by WL0627** [comment]
> 你的list地址直接填你反代的https地址就可以了

alist地址要求不能加Http或者https,只能ip+端口，默认生成的strm 就是http

**Comment by WL0627** [comment]
> > 你的list地址直接填你反代的https地址就可以了
> 
> alist地址要求不能加Http或者https,只能ip+端口，默认生成的strm就是http

![微信图片_20240118154250](https://github.com/shenxianmq/Auto_Symlink/assets/29673960/1fb50c34-b7b8-4a6e-8762-456da4c29546)

**Comment by shenxianmq** [comment]
这个我倒是忘记了，你的alist和as在一个设备上吗？如果在一个设置上的话直接填内网地址就可以了

**Comment by shenxianmq** [comment]
这个问题我已经修复了，你可以更新一下镜像，然后可以在云端地址里填写https://试一下

**Comment by WL0627** [comment]
> 这个问题我已经修复了，你可以更新一下镜像，然后可以在云端地址里填写[https://试一下](https://%E8%AF%95%E4%B8%80%E4%B8%8B)

大佬  测试可以了。但是你的前台因该是加了限制的输入http或者https就不能保存，我去docker配置文件改的  可以生效了  感谢

**Comment by shenxianmq** [comment]
这个问题我也解决了，你过5分钟更新一下镜像即可

**Comment by WL0627** [comment]
> 这个问题我也解决了，你过5分钟更新一下镜像即可

已更新，也太肝了吧
