### ISSUE TITLE
希望能增加自动同步strm后联动批量重命令功能

### ISSUE THREAD

**Issue by renlixing87** [shenxianmq/Auto_Symlink#13]
最在使用这个软件配置小雅，能实现刮削小雅，实现emby上的海报功能，使用autosymlink+加了nastool联动真是神器，但目前试验下来还不能实现全自动，我的实现方法如下：
autosymlink同步小雅目录，但由于小雅上资源命名太乱，有的名称中有4k\1080p等实际检测，有的名称直接就是01、02、03这种资源emby、nastool是无法识别的，所以我现在是用autosymlin中的批量重命名去除4k\1080字样，再用剧集命名实现在01、02、03资源加上文件夹名称，这样资源就差不多能让nastool刮削nfo文件了，我的需求如下:

在自动同步strm文件后，能自动联通批量重命名和剧集命名功能实现规范命名功能，然后再由nastool自动刮削nfo文件，这样全程我就不用再手动 了，能实现类型devops流水线的功能

**Comment by shenxianmq** [comment]
就阿里云那个资源的命名，有时候文件夹名根本就不是剧集名，你如何确定自动命名就一定准确呢，还是手动最稳妥

**Comment by WL0627** [comment]
nastool不支持小于150M的文件刮削

**Comment by shenxianmq** [comment]
> 就阿里云那个资源的命名，有时候文件夹名根本就不是剧集名，你如何确定自动命名就一定准确呢，还是手动最稳妥



> nastool不支持小于150M的文件刮削

谁告诉你不支持了，配置选项里有，自己看一下
