### ISSUE TITLE
大佬，strm会自己失效吗

### ISSUE THREAD

**Issue by aprilowolovejiuwang** [shenxianmq/Auto_Symlink#19]
我有时同步文件，查看日志发现 自动删除无效strm、和添加新的strm。我用的cd2挂载谷歌和阿里云，但网盘文件都只是添加 没有变动其他文件，
strm会自己失效吗

**Comment by shenxianmq** [comment]
更新一下镜像就行，已经修复这个问题了

**Comment by aprilowolovejiuwang** [comment]
收到，谢谢大佬

**Comment by aprilowolovejiuwang** [comment]
> 更新一下镜像就行，已经修复这个问题了

![image](https://github.com/shenxianmq/Auto_Symlink/assets/109020274/ec164d3a-aec8-474b-b199-d50c8925fbfe)
![image](https://github.com/shenxianmq/Auto_Symlink/assets/109020274/54fedd33-a339-4394-9580-b999b8dc4477)
大佬还是出现这个问题

**Comment by shenxianmq** [comment]
重新更新一下，昨天没有推送成功

**Comment by aprilowolovejiuwang** [comment]
好勒
