### ISSUE TITLE
建议增加文件权限运行

### ISSUE THREAD

**Issue by ihnic** [shenxianmq/Auto_Symlink#2]
我使用的是docker，但是创建出来的文件权限为root，作者能否增加UID、GID文件权限执行

**Comment by atpx4869** [comment]
同上...  unraid读取不到映射文件夹内的文件

**Comment by shenxianmq** [comment]
这个问题已经解决，创建容器时添加
user 1000:1000就可以以普通用户权限运行

**Comment by fishinsevens** [comment]
> 这个问题已经解决，创建容器时添加
> user 1000:1000就可以以普通用户权限运行

请问大佬unraid下要怎么填写模板实现这个权限呢

**Comment by ihnic** [comment]
谢谢处理
不过我发现创建文件夹时是以root创建
