### ISSUE TITLE
大佬你好，关于群晖安装的问题

### ISSUE THREAD

**Issue by szkeum** [shenxianmq/Auto_Symlink#23]
用命令行安装，最后提示错误运行不了，可能问题出现在rslave上面，请问怎么操作

**Comment by szkeum** [comment]
<img width="626" alt="群晖" src="https://github.com/shenxianmq/Auto_Symlink/assets/119716280/f55d82be-149d-4195-8acf-a58044844af5">

**Comment by karasfjm** [comment]
试试设置里面删除后手动添加

**Comment by ladiosfei** [comment]
我也是同样的情况，群晖7.2，试了很多次手动安装都不成功，后来只有把rslave参数改为RW才行，不知道实际使用时会不会有影响。
后来解决了，先要用mount，把存储空间标记成shared，然后再手动运行docker run就成功了

**Comment by shenxianmq** [comment]
在群晖的任务计划中添加开机任务：
mount --make-shared /volume1/
mount --make-shared /volume2/
systemctl daemon-reload
添加后手动运行一次，之后开机会自动运行

**Comment by ladiosfei** [comment]
感谢分享，这个方法实测有效




发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: "沈闲" ***@***.***>
 

 
 发送时间: 2024-03-18 19:34:53
 

 
 收件人: shenxianmq/Auto_Symlink  ***@***.***> 
 

 
 抄送: ladiosfei  ***@***.***>,Comment  ***@***.***> 
 

 
 主题: Re: [shenxianmq/Auto_Symlink] 大佬你好，关于群晖安装的问题 (Issue #23)
 





 在群晖的任务计划中添加开机任务：
 mount --make-shared /volume1/
 mount --make-shared /volume2/
 systemctl daemon-reload
 添加后手动运行一次，之后开机会自动运行
