### ISSUE TITLE
CloudDrive2 生成的 strm 文件地址有误

### ISSUE THREAD

**Issue by oevery** [shenxianmq/Auto_Symlink#28]
生成的strm文件访问提示404，对比后发现False后面应该有两个//，生成的 strm 文件只有一个

`http://homelab:19798/static/http/homelab:19798/False%2F115%2Fbili-videos%2F%E4%B8%8D%E5%A6%82%E8%B7%B3%E8%88%9E%2FBV11a4y1C7Jh.mp4`

`http://homelab:19798/static/http/homelab:19798/False//115%2Fbili-videos%2F%E4%B8%8D%E5%A6%82%E8%B7%B3%E8%88%9E%2FBV11a4y1C7Jh.mp4`

上面的是生成的，下面的是复制出来的，可以看到 False 后面的 // 不一致。

**Comment by shenxianmq** [comment]
更新一下镜像即可

**Comment by oevery** [comment]
> 更新一下镜像即可

更新后正常了。
