### ISSUE TITLE
发现一个问题，软链接模式

### ISSUE THREAD

**Issue by bulesky89857** [shenxianmq/Auto_Symlink#29]
服务都在我的Linux服务器上，选择symlink后emby无法播放视频，改为strm后恢复正常，不知道为什么？

**Comment by shenxianmq** [comment]
emby也要把cd2的绝对路径进行挂载，比如/volume1/cd2:/volume1/cd2:rlsave，确保右边的路径和左边的一模一样

**Comment by bulesky89857** [comment]
> emby也要把cd2的绝对路径进行挂载，比如/volume1/cd2:/volume1/cd2:rlsave，确保右边的路径和左边的一模一样

一摸一样,只有strm模式有效,今天又出现一个问题,昨天配置同步文件夹,今天在登录auto,symlink 全部配置的数据都没了,docker部署的,奇了怪了

**Comment by bulesky89857** [comment]
明白了，是emby里面也要把网盘的路径挂载进去，😂😂😂😂😂😂😂2024年3月6日 18:40，沈闲 ***@***.***>写道：
emby也要把cd2的绝对路径进行挂载，比如/volume1/cd2:/volume1/cd2:rlsave，确保右边的路径和左边的一模一样

**Comment by bulesky89857** [comment]
> emby也要把cd2的绝对路径进行挂载，比如/volume1/cd2:/volume1/cd2:rlsave，确保右边的路径和左边的一模一样

不好意思 ,眼拙没看见您写的是'emby也要把cd2的绝对路径进行挂载',今天无意清理邮件才发现您写的是'emby'  ,谢谢!
