### ISSUE TITLE
bdmv有没有在技术上支持，iso呢

### ISSUE THREAD

**Issue by raylapse** [shenxianmq/Auto_Symlink#30]
可能是个小白问题哈，打扰大佬了
我听说iso不支持生成strm是真的吗？
然后我本地下载的bdmv这种，我也想通过strm方式把元数据跟原始bdmv分开，类似nastool的硬链接概念
有可能实现吗？strm是不是不可能指向一个文件夹？

**Comment by shenxianmq** [comment]
bdmv本身stream文件夹里的最大的m2ts文件就是电影对应的文件，建议直接把这个文件提取出来进行刮削

**Comment by raylapse** [comment]
是的，但是手工提炼太麻烦了，每个bd不相同，不知道as方便不方便在detect到是bdmv文件夹时，自动lookup playList文件夹下最大的那个mpls文件生成.strm文件
