### ISSUE TITLE
alist挂载类型生产地址多了一个“/”

### ISSUE THREAD

**Issue by lucifer-j** [shenxianmq/Auto_Symlink#31]
环境：unraid
挂载情况：使用clouddrive2以webdav的方式挂载小雅超集
生成路径：http://192.168.31.215:5678/d/%2F%E5%8A%A8%E6%BC%AB%2F%E5%84%BF%E7%AB%A5%2F%E4%B8%AD%E5%8D%8E%E7%BB%8F%E5%85%B8%20-%20%E5%AD%97%E6%9C%89%E9%81%93%E7%90%86%2F%E5%AD%97%E6%9C%89%E9%81%93%E7%90%86%20%E7%AC%AC%E4%BA%8C%E5%AD%A3%2F%E7%AC%AC3%E5%8D%95%E5%85%83%E7%AC%AC2%E8%AF%BE%2F60%20%E7%BE%8E.MP4
解码后：http://192.168.31.215:5678/d//动漫/儿童/中华经典 - 字有道理/字有道理 第二季/第3单元第2课/60 美.MP4

动漫前多了一个“/”

**Comment by shenxianmq** [comment]
更新下镜像即可，这个问题已经修复了

**Comment by lucifer-j** [comment]
> 更新下镜像即可，这个问题已经修复了

已经更新最新的镜像了，显示版本为2.1.2

**Comment by lucifer-j** [comment]
> > 更新下镜像即可，这个问题已经修复了
> 
> 已经更新最新的镜像了，显示版本为2.1.2

我是docker部署的

**Comment by shenxianmq** [comment]
我刚刚才推送的，你更新下就行，版本号并不有修改

**Comment by lucifer-j** [comment]
> 我刚刚才推送的，你更新下就行，版本号并不有修改

测试OK了，谢谢
