### ISSUE TITLE
请教一下实时监控功能的问题

### ISSUE THREAD

**Issue by nefelibatawu** [shenxianmq/Auto_Symlink#34]
目前我遇到的问题就是同步功能是正常运行的，但是实时监控的功能看上去是没有起作用。
这里我想问一下实时监控功能是我理解的网盘这边文件内容发生修改，auto_symlink就会自动刷新strm以及元数据吗？

**Comment by shenxianmq** [comment]
实时监控，监控的是cd2的挂载文件夹，因此想要监控生效的话，对于文件操作，有两种方法可以生效：
1.本地文件操作
2.在cd2网页版里操作
在官方的app或者网页版中操作是不会监控到的，因为cd2不知道发生了变更，只有自己手动刷新才会更新，因此不会触发实时监控

**Comment by nefelibatawu** [comment]
了解了，多谢解惑
