### ISSUE TITLE
用alist方式挂载，生成strm，缺少一个/。

### ISSUE THREAD

**Issue by Swiftfrog** [shenxianmq/Auto_Symlink#37]
系统：Debian12
挂载方式：davfs2 挂载alist/dav

生成地址后，strm文件内容为：
https://IP:端口/dALI-RESOURCE%2FB%2FBlossoms.Shanghai.2023.S01E27.2160p.WEB-DL.HEVC.10bit.DV.DDP.4Audios.mp4
dALI应当为d/ALI

可以麻烦看一下吗？

**Comment by shenxianmq** [comment]
更新一下镜像，刚刚修复了这个问题

**Comment by Swiftfrog** [comment]
> 更新一下镜像，刚刚修复了这个问题

非常感谢，已经好了。

这个速度超快的，谢谢。
