### ISSUE TITLE
可否支持Alist挂载的绝对路径？

### ISSUE THREAD

**Issue by Swiftfrog** [shenxianmq/Auto_Symlink#38]
用alist的dav挂载，然后生成文件的绝对路径，如下：
**xxx.strm:
/Ali/文件夹/文件夹/文件名.mp4**

这样的好处是，strm文件没有泄露风险。

配合[embyExternalUrl](https://github.com/chen3861229/embyExternalUrl)，可以转直链。

如果可以，感谢。

**Comment by shenxianmq** [comment]
已经支持了
