### ISSUE TITLE
外网通过IPv6访问不了WebUI

### ISSUE THREAD

**Issue by LunaticXJ** [shenxianmq/Auto_Symlink#46]
由于申请不到公网IPv4，故通过IPv6外网访问家里的NAS，现在Docker模式安装后，使用host网络模式访问不到Auto_Symlink的WebUI，而其他host模式安装的应用（如emby）通过外网IPv6是可以正常访问的

**Comment by liuhangbin** [comment]
我用的birdge模式，IPv6可以访问WebUI

**Comment by LunaticXJ** [comment]
用群晖的反向代理搞定了
