### ISSUE TITLE
软链接同步希望能支持改名后的软链接

### ISSUE THREAD

**Issue by raylapse** [shenxianmq/Auto_Symlink#50]
目前如果爬下来的软链接改名后，再同步一次会删除改名的软链接并重新生成一个新的。
但其实改名的软链接一样是有效的，且对影库整理有极大帮助。

希望同步时，检查软链接是否存在的依据，不是单靠文件名，而是检查软链接指向的实际文件。
如果实际文件有效，则保留原来的软链接，而不是重新生成一个。

**Comment by shenxianmq** [comment]
这个问题已经解决，更新即可
