### ISSUE TITLE
建议：是否可以在不用cd2的情况下生成strm（域名的）

### ISSUE THREAD

**Issue by kingtalk** [shenxianmq/Auto_Symlink#51]
是否可以通过使用alist路径，如：https://域名:端口/d/115……这种路径，配合存储strm路径，在配合alist token生成域名的strm，这样就可以节约一个挂载环节。

**Comment by shenxianmq** [comment]
AS主要面对cd2用户，所以没有这个计划.

**Comment by lpdswing** [comment]
单纯生成strm文件的话可以用小雅的脚本, 然后批量替换xiaoya.host:5678为你的alist地址, 这个工具要挂载目录感觉还是有些麻烦
