### ISSUE TITLE
复制模式不生效

### ISSUE THREAD

**Issue by totobo** [shenxianmq/Auto_Symlink#54]
操作步骤：
1. 同步功能的元数据模式选择的本地模式
2. 在本地目录更新nfo文件（emby扫描媒体文件后添加的信息）
3. 点击手动同步

测试结果：
1. 本地nfo文件的内容被网盘上的覆盖了
4. 本地修改的图片poster.jpg，在执行完手动同步之后，也被覆盖成网盘上的旧内容了

**Comment by shenxianmq** [comment]
不想被覆盖就开启元数据跳过
