### ISSUE TITLE
部分媒体图片和nfo下载失败

### ISSUE THREAD

**Issue by wangliangdong** [shenxianmq/Auto_Symlink#64]
媒体文件时alist/CD2挂载在NAS本地，Auto_Symlink生产Strm和下载元数据到link对应的文件夹，大部分都是可以的，但就是有三个视频的nfo和图片信息下载不了，不知道为什么
![1](https://github.com/user-attachments/assets/b5eea4f2-038a-4be3-bea9-41e7eaf4d963)
![2](https://github.com/user-attachments/assets/92443649-cca3-406d-90d3-6545d40a58e1)
![3](https://github.com/user-attachments/assets/1745b19f-2ade-4d1a-b09b-6d77baf29a15)

**Comment by shenxianmq** [comment]
说明源文件本身有问题
