### ISSUE TITLE
元数据复制和无效检测是否有问题？？？

### ISSUE THREAD

**Issue by qq1620** [shenxianmq/Auto_Symlink#66]
今天更新元数据，设置了元数据跳过，他还是会给复制一份*(1).nfo这类的元数据下来，本地有这个nfo文件，然后我想启用删除无效元数据去掉这些带（1）的文件，结果媒体库除了strm文件，其它文件全被删除干净了

**Comment by shenxianmq** [comment]
同步下来说明你网盘有这个元数据，至于元数据被删除说明是你配置问题或者掉盘了

**Comment by qq1620** [comment]
是的，有些网盘有这个元数据，但是我点了元数据跳过。首次启用元数据跳过是否需要先重启一次AS呢

沈闲 ***@***.***> 于2024年10月3日周四 17:15写道：
